[package]
name = "btc-relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoincore-rpc = "0.18.0"
near-jsonrpc-client = "0.9.0"
near-jsonrpc-primitives = "0.21.2"
near-primitives = "0.21.2"
reqwest = "0.11.27"
tokio = "1.37.0"
env_logger = "0.11.3"

